= Zusammenfassung

Mit Kotlin und Kotlin Multiplatform haben wir ein Konzeptapp entwickelt<LINK 9>, welche die Vorteile der Sprache als moderne und gut lesebare Programmiersprache dokumentieren soll. Es ist immer wieder erfreulich festzustellen, wie mächtig Kotlin und die Standard-Bibliothek von Kotlin sind, sodass man mit hauseigenen Mitteln wie coroutines und Flow früher sehr aufwendig zu implementierende Konzepte wie asynchrone Programmierung elegant umsetzen kann. Jetpack Compose sogar weiter und mit der Unterstützung von Kotlin ist es möglich, reaktive Bedienoberflächen deklarativ zu entwickeln. Die Idee, das man kann auch an nicht visuelle Elemente der App die Composable Funktionen mit ihrer Fähigkeit, einen Status zu halten, zu verwenden und auf Veränderung mit recomposition zu reagieren, zeigt auch die Stärke von Jetpack Compose. Ein Zusammenspiel mit einer durchdachten Architektur macht das Entwicklen einer moderner HMI App möglich.
Neben der Technik haben wir auch festgestellt wie wichtig die SoftSkills sind und wie sich Kotlin in multiplatform Teams anfühlt und etablieren kann.