= Geteilte Freude ist doppelte Freude

Eins von dem Zielen, die wir uns für die App gesetzt haben war, dass die App auf unterschiedlichen Betriebssystemen und Endgeräten laufen kann. Natürlich zu entwickeln eine separate App für jede Platform ist aufwendig und das aus vielen Aspekten (Entwickler mit entsprechenden Fähigkeiten, Kosten, Zeit oder Wartbarkeit als einigen zu nennen) an der anderen Seite ist die native Leistung oder die Art wie sich die App in jeweiliger Ökosystem anfühlt oder integrieren lässt. Man war
von Anfang an auf der Suche dem perfekten Weg. Angefangen mit HTML5-basierten Web-Apps (Cordova, Ionic), mit schwergewichtigen Cross Platform Frameworks wie Xamarin, bis zu hybriden Ansätzen wie React Native, Vue Native oder Flutter. Alle haben ihre Vor und Nachteile.  Als eine ernstzunehmende Alternative zeichnet sich Codesharing mit Kotlin in Multiplatform-Projekten ab, wo in Kotlin geschriebener Code auf  unterschiedlichen Plattformen laufen kann.
Das Thema ist nicht neu und wurde schon oftmals behandelt(als ein Beispiel das Link auf Artikel in Java Aktuell 01 2020). Mit der Zeit haben sich Grunde für Code sharing mit Kotlin nicht nur bestätigt, sondern sind auch mit wie mit zum Beipiel Jetpack Compose weitere neue dazu gekommen.
