= Geteilte Freude ist doppelte Freude

Eines der Ziele, die wir uns für die App gesetzt haben war, dass die App auf unterschiedlichen Betriebssystemen und Endgeräten laufen soll. Eine separate App für jede Platform ist einerseits aufwendig, und das aus vielen Gründen (Entwickler:innen mit entsprechenden Fähigkeiten, Kosten, Zeit oder Wartbarkeit etc). Auf der anderen Seite steht die native Leistung oder die Art wie sich die App in ihren jeweiligen Ökosystemen anfühlt oder integrieren lässt. Die Suche nach dem perfekten Weg ist schon alt. Für Mobile Apps liegt der Anfang vermulich bei HTML-basierten Web-Apps (Cordova, Ionic), mit schwergewichtigen Cross Platform Frameworks wie Xamarin, bis zu hybriden Ansätzen wie React Native, Vue Native oder Flutter. Alle haben ihre Vor und Nachteile.  Als eine ernstzunehmende Alternative zeichnet sich Codesharing mit Kotlin in Multiplatform-Projekten ab, wo in Kotlin geschriebener Code auf unterschiedlichen Plattformen laufen kann.
Das Thema ist nicht neu und wurde schon öfter behandelt (Beispielsweise in Java Aktuell 01/2020). Mit der Zeit haben sich die Vorteile für Code Sharing mit Kotlin nicht nur bestätigt, sondern es sind auch mit weitere neue dazu gekommen, wie zum Beispiel Jetpack Compose.
