= IoT

IoT ist ein sehr breiter Begriff und beinhalten nicht nur unterschiedliche Geräte Typen und Fähigkeit, die sie verfügen, aber auch eine Menge von Protokollen, die sie sprechen. Plc-Explorer benötigt nur eine kleine Untermenge den Merkmalen, die die Geräte und Protokolle anbieten, damit ist die Vielfälligkeit mit relative einfache Abstraktion zu lösen. Die Geräte sind in Bäumen organisiert und deren Eigenschaften wie die Werte oder Einstellungen sind als Knoten untergeordnet. Manche Protokolle wie z.B. KNX unterstützen ein Discovery Mechanismus, der ermöglicht die Geräte im Netzwerk zu entdecken, bei manchen muss die Geräte selber anlegen und entsprechen Eigenschaften wie Netzwerk Addressed und Belegung selber zu definieren.

Eine Abstraktion können wir analog zu ein Betriebssystem als ein Treiber zu definieren.

== Integration in Kotlin Multiplatform

Die einfachste und natürlich auch die schönste Variante um ein Geräte driver samt Communications Protocol zu integrieren ist ein in Kotlin Multiplatform geschrieben Implementieren. Dadurch dass Kotlin und gerade Kotlin Multiplatform noch sein Weg in die Breite Entwickler Community noch sucht, gibt es davon nicht viel. Hier zeig aber Kotlin wiederum seine Stärken, die sher gute Interoperabilität mit JVM, so man auf bestehende JVM Bibliotheken zugreifen kann und mit Kotlin Native eine möglichkeit, gerade beim iOS sehr interessant, eine native Implementierung des Protokolls in ein Kotlin Geräte Treiber einzubinden.

== Integration in Coroutines/Flows

=== API with callback

Mit suspendCancellableCoroutine

[source, kotlin]
----
private suspend fun awaitLoggedIn(): LoginResuk = suspendCancellableCoroutine { continuation ->
        val callback = object : Callback<Tokens> {
            override fun onResult(result: Tokens) {
                // Signed in
                continuation.resume(LoginToken(result.token)) { cancelationThrowable ->

                }
            }

            override fun onError(e: java.lang.Exception) {
                // error
                continuation.resume(LoginError) {
                }
            }
        }
        ApiWithClient.getTokens(callback)
    }
----