= Kotlin und Kotlin Mutliplatform

Warum überhaupt Kotlin? Code sharing ist  nichts Neues und funktioniert auch mit anderen Programmiersprachen.
Zunächst ist es Kotlin als Sprache selbst: Kotlin bezeichnet sich als kompakt und präzise, sicher, ausdrucksvoll, vollständig kompatibel und multiplatform fähig. Schon aleine die ersten Eigenschaften machen Kotlin gerade für Java Entwickler:innen interessant. Und für unsere IoT App spielt gerade die Multiplatorffähigkeit eine bedduetende Rolle. Ein wichtiger Teil der Kotlin multiplatformfähig macht, sind in die Sprache selber integrierte Schlüsselwort *expected/actual*, die ein fester Bestandteil der Programmiersprache sind.

Ein weiterer wichtiger Baustein, der das Bauen von reaktiven Apps vereinfacht und zur Sprache selber gehört, sind coroutines und Flows. Generell läuft die Kommunikation mit den Geräten im Hintergrund, dazu kommt dass wir mit mehrere Geräten gleichzeitig Daten austauschen wollen. Das wird durch Einsatz asynchroner Programmierung gelöst, bei der die einzelnen Abfragen nicht mehr hintereinander, sondern parallel ausgeführt werden. Das Aktualisieren der Bedienoberfläche findet nur in einem (anderen) Thread statt. Solcher Code ist normalerweise nicht einfach zu schreiben, und wenn dann auch noch Bildschirmrotation hinzukommt, die eine neue Anzeige des Objekts erfordert (bekannt als Activity Lifecycle) sind die schlaflosse Nächste beim Debuggen vorprogrammiert.

Kotlin löst das Problem mit dem Schlüsselwort *suspend* und führt ein Programmierparadigma benannt als *Strukturierte Parallelität* (structured concurency) ein. Die Hauptidee ist das Kapseln der Ausführung von parallelen Ausführungen in eigenen Blöcken, so dass der zuständige Code zusammen mit einem klarem Anfang und Ende geschrieben ist. Dies erzeugt nicht nicht nur besere Lesbarkeit und Fehlerbehandlung, sondern auch besseren Resource Management mit Resourcen wie zum Beispiel Threads.

Eine vollständige kompatibilität zum JVM war und bleibt eins der Hauptmerkmale vom Kotlin und erlaubt uns auch beim Thema Kotlin Multiplatform die Integration von JVM Bibliotheken. Gerade in Bereich maschinenorientierter Protokolle ist die Auswahl von qualitativ hochwertigen Bibliotheken sehr gut. Als Beispiele sind die Bibliotheken für die Kommunikation in KNX oder das Apache Projekt PLC4X mit mehreren SPS Protokollen im Portfolio (siehe Projekt Homepage https://plc4x.apache.org/)

Kotlin hat noch ein weiteres Ass im Ärmel: Kotlin/Native. Kotlin/Native is eine Technologie, die das Kompilieren vom Kotlin Code in den nativen binären Code erlaubt, der ohne eine virtuelle Maschine laufen kann. Kotlin/Native beinhalted ein LLVM basiertes Backend für den Kotlin Kompiler und eine native Implementierung der Kotlin Standard Bibliothek. Das ist genau der Weg, wie wir die nativen iOS und macOS Apps in Kotlin bauen können.
