= Kotlin und Kotlin Mutliplatform

Warum überhaupt Kotlin. Code sharing ist doch nichts Neues und funktioniert auch mit anderen Programmiersprachen.
Zuerst ist es Kotlin als die Sprache selber. Kotlin selber bezeichnet sich als kompakt und präzise, sicher, ausdrucksvoll, vollständig kompatibel und multiplatform fähig. Schon aleine die ersten Eigenschaften machen Kotlin gerade für die Java Entwickler interessant. Für die unsere IoT App spiel gerade die Multiplatorffähigkeit eine bedduetende Rolle. Ein wichtiger Teil der Kotlin multiplatformfähig macht, sind in die Sprache selber integrierte Schlüsselwort *expected/actual*, die ein fester Bestandteil der Programmiersprache sind.

Weiteres wichtiges Baustein, der das Bauen von reaktiven Apps vereinfacht und zur Sprache selber gehören, sind coroutines und Flows. In Generellen läuft die Kommunikation mit den Geräten im Hintergrund, dazu kommt dass wir mit mehrere Geräten gleichzeite die Daten austauschen wollen. Das lösst man mit dem EInsatz der Asynchronnem
Programmierung, bei denen die einzelnen Abfragen nicht mehr hintereinander, sondern parallel gelöst werden. Wiederum das Aktualisieren der Bedienoberfläche ist nur in einem, normalweise als Main genanntem Thread. So ein Kod ist nicht einfach zu schreiben, wenn wen dazu kommt, wie zum Beipiel am Android eine Bildschirmrotation das Objekt zustendig für die Anzeige neu erzeugt (bekannt als Activity Lifecycle) sind die schlaflosse Nächste beim Debuggen vorprogrammiert.

Kotlin löst das Problem mit dem Schlüsselwort *suspend* und führt ein Programmierparadigma  benannt als *Strukturierte Parallelität* (structured concurency) ein. Die Hauptidee ist das Kapseln der Ausführung von parallelen Ausführungen in die eigenen Blöcke, so das der zuständige Kode  zusammen mit klarem Anfang und Ende geschrieben ist. Es erlaub nicht nur besere Lesbarkeit, Fehler Behandlung aber auch besseren Resource Management mit resourcen wie Thrads.

Eine vollständige kompatibilität zum JVM war und weiterhin bleibt eine von Hauptmerkmalen vom Kotlin und erlaubt  uns auch beim Thema Kotlin Multiplatform die Integration von JVM Bibliotheken. Gerade in Bereich von maschinenorientierte Protokolle ist die Auswahl von qualitativ hochwertigen Bibliotheken gut.Als Beispile kann man die Bibliotheken für die Kommunikation in KNX oder das Apache Projekt PLC4X mit mehreren SPS Protokollen im Portfolio(siehe Projekt Homepage https://plc4x.apache.org/)

Kotlin hat noch ein weiteres Ass im Ärmel. Kotlin/Native. Kotlin/Native is eine Technologie, die erlaubt das Kompilieren vom Kotlin Kode in den nativen binären Kode, der ohne eine virtuelle Maschine laufen kann. Kotlin/Native beinhalted ein LLVM basiertes Backend für Kotlin Kompiler und eine native Implementirung der Kotlin standard Bibliothek. Das ist genau der Weg, wie wir die nativen iOS und MacOS Apps in Kotlin bauen könne.
