= Zusammenfassung

Mit Kotlin und Kotlin Multiplatform haben wir ein Konzept App enticklet, die Vorteile der Sprache,  ist eine moderne Programmiersprache, die erlaubt nicht nur ein gut lesbaren. Es ist immer wieder erfreulich festzustellen, wie mächtig Kotlin und die Standard Bibliothen von Kotlin sind, sodass man mit hauseigenen Mitteln wie coroutines und Flow früher aufwendige Konzepte wie asynchrone Programmierung elegant umsetzen kann. Jetpack Compose geht ein oder sogar mehre Schritte weiter und mit der Unterstützung von Kotlin Compiler ist es möglich reaktive Bedienoberflächen deklarativ zu entwickeln. Die Idee, das man kann auch an nicht visuelle Elemente der App die Composable Funktionen mit deren Fähigkeiten Status zu halten und auf Veränderung mit recomposition reagieren, zeigt auch die Stärke von dem Jetpack Compose. Ein Zusammenspiel mit einer durchgedachter Architektur macht das Entwicklen eine moderner HMI App möglich.
Neben der Technik haben wir auch festgestellt wie wichtig die SoftSkills sind und wie sich Kotlin in multiplatform Teams anfühlt und etablieren kann.