= Responsive Multiplatform HMI-Anwendungen mit Kotlin Multiplatform und Jetpack Compose
Firstname Lastname <michal@harakal.de>
3.0, July 29, 2022: AsciiDoc article template
:toc:

:imagesdir: images

Mit fortgeschrittener Digitalisierung wachsen Anforderungen auch auf die HMI-Anwendungen in verschiedenen industriellen Bereichen.
Nicht nur sicher, zuverlässig und schlank, aber auch modern, gut aussehend und vernetzt sollten sie werden.
Mit einer einfachen Desktop-App, die mehrere Protokolle beherrscht, schauen wir uns in diesem Artikel die Stärken von Kotlin und Kotlin Multiplatform, wie man einfach mehrere Plattformen Desktop und Mobil (besonders mit Fokus auf Betriebssysteme von Apple) ohne Kompromissen unterstützen kann, wie wunderbar die Interoperabilität zwischen Kotlin und JVM funktioniert und wie deklarative UI Frameworks, wie Jetpack Compose und Swift UI, die Art und Weise verändern, wie man reaktive Bedienoberfläche heutzutage entwickelt.


include::sections/hmi_app.adoc[leveloffset=+1]

include::sections/code_sharing.adoc[leveloffset=+1]

include::sections/kotlin.adoc[leveloffset=+1]

include::sections/architecture.adoc[leveloffset=+1]

include::sections/gradle.adoc[leveloffset=+1]

include::sections/jetpack_compose.adoc[leveloffset=+1]

include::sections/ui.adoc[leveloffset=+1]

include::sections/ios.adoc[leveloffset=+1]

include::sections/summary.adoc[leveloffset=+1]
